### ISSUE TITLE
Issue with TorProxy in Docker Compose: Receiving Status Code 490

### ISSUE THREAD

**Issue by ParsaMehdipour** [shahradelahi/docker-torproxy#15]
I am using TorProxy in my Docker Compose setup and routing my requests through Polipo via the Tor proxy. However, after some time, I start receiving responses with a status code of 490.

Could this issue be related to the Tor proxy, or do I need to refactor my code?

Any insights would be appreciated.

**Comment by shahradelahi** [comment]
Hi @ParsaMehdipour,

It might be related to the proxy. Please provide more details and the code snippet of your docker-compose if it's possible.

Check your connectivity to the Tor network [README: `Testing`](https://github.com/shahradelahi/docker-torproxy#testing). 

The container by default has a health check. Also, check the container logs for any obvious warnings or errors that might be causing the issue.

**Comment by shahradelahi** [comment]
What's Polipo? Is it a caching web proxy server? My best guess is the error is from your Polipo. If it was from tor proxy, you were facing timeouts or service unavailable errors.
